### ISSUE TITLE
Ultime modifiche

### ISSUE THREAD

**Issue by Bonny91** [loribonna/InfomontCAI#2]
- Nome rifugio: più piccolo (va bene di -1)
- Località accanto al map marker più piccola (ok - 1) 
- l'ordine dell'elenco è: 1) sezione 2) tipo rifugio. (quindi da invertire rispetto ora)
- inserire una x per chiudere la fotografia (in alto a destra)

**Comment by Bonny91** [comment]
- Nella barra in alto togliere rifugi e lasciare solo Infomont.

- Aumentare l'interlinea tra il nome del rifugio località e coordinate. Invece, l'interlinea delle righe sotto  (sezione ecc) va bene.
- Rimpicciolire di un px i nomi delle tabs.
- Rinominare la sezione "Posizione" in "Descrizione".

- Nella sezione "Descrizione":
   a) Sotto la "Categoria" inserire lo "Stato".
    b) in UnicoCAI: ampliare lo spazio della sezione "Sito" (da 4 a 8 righe). 
    c) Verificare che nell'importazione del campo "Sito" da UnicoCAI a Excel non ci siano dei problemi coi caratteri speciali (questo lo faccio io). 
    d) Verificare che vada a capo bene.

- Nella sezione "Servizi" andranno visualizzati solo i seguenti servizi, nel seguente ordine. Il nome da scrivere accanto alle icone è quello riportato qui:
 - Posti letto: fa-bed   (a fianco il numero di posti letto)
 - Vendita sacco lenzuolo: fa-box-check     (se non c'è non si mette)
 - Ristorante: fa-utensils       (se non c'è non si mette)
 - Accesso alla cucina: fa-cauldron         (se non c'è non si mette)
  - Acqua in rifugio: fa-tint COLORE BLU      (se non c'è non si mette)
  - Acqua calda in rifugio: fa-tint   COLORE ROSSO     (se non c'è non si mette)
  - Docce: fa-shower     (se non c'è non si mette)
 - Elettricità in rifugio: fa-bolt    (se non c'è non si mette)
  - Punti ricarica: fa-plug      (a fianco il numero)
 - WIFI disponibile: fa-wifi       (se non c'è non si mette)
 - Segnale GSM: fa-signal        (se non c'è non si mette)
 - Accessibilità: fa-wheelchair    (se non c'è non si mette)
 - Pagamento con carte: fa-credit-card      (se non c'è non si mette)
 - Attività: fa-star     (se non c'è non si mette)



- Mettere insieme la sezione apertura e contatti. Nella prima riga, ci vanno le aperture. Nella seconda riga, i contatti (vanno bene quelli che ci sono ora). Per ultimi ci vanno: 
     - Ritiro chiavi:  fa-key     (se non c'è non si mette)
      - Autogestione: fa-users       (se non c'è non si mette)
 
-  Nella sezione "Proprietà": togliere il dato "Certificazione".
- (ULTIMA MODIFICA DA CALL 09/01/19): eliminare attività culturali.

**Comment by Bonny91** [comment]
Come si vede dal **rifugio al cedo** (su heroku compilato debitamente):
- Maschera in alto:
 1) non prende i dati sezione e stato;
  2) Dopo lo stato prende il campo sito, toglierlo. Il campo sito va nella sezione "descrizione".
  3) Mettere in grassetto il nome del rifugio
  4) la località accanto al map marker va della stessa grandezza degli altri campi (categoria ecc).
  5) Mettere le coordinate metterle di seguito alla località, compresa l'altitudine.

- Descrizione:
1)  tra il gruppo montuoso e la valle ci va una virgola;
2)  dopo "in area" non deve andare a capo, ma farla su tutta una riga. 
 3) Il campo "in area" deve andare prima del campo "sito", il quale risulterà essere l'ultimo. 
4) Dopo "Nel" ci vuole uno spazio. 

- Servizi: li replica più volte su due colonne, controllare

- Aperture e contatti:
i due titoletti, aperture e contatti, farli in grassetto.

- Proprietà e struttura:
aumentare l'interlinea tra la riga separatrice e il testo sopra e sotto.

- Foto: si riesce a prevedere il basso a sinistra la visualizzazione della didascalia?

**Comment by loribonna** [comment]
Mettere didascalia in mezzo
Spazio tra la data e al in aperture
