### ISSUE TITLE
Graphical enhancements

### ISSUE THREAD

**Issue by loribonna** [loribonna/InfomontCAI#3]
- If a field is null, should visualize nothing instead of character '-',
 - Remove self_management icon in 'Apertura e contatti',
 - Avoid vertical scoll-bar,
 - Add role string for fields in contacts (now it's statically typed 'Gestore')

**Comment by Bonny91** [comment]
1) Dobbiamo anche fare in modo che le informazioni siano visibili con lo stesso ordine, quindi soprattutto i servizi: se, per esempio, un utente vuole confrontare due rifugi, deve poterlo fare in modo chiaro.

2) Come si dice qua (https://material.io/design/layout/density.html#usage) sarebbe meglio inserire uno spazio predefinito a sinistra, prima che inizi la scritta (cioè, il margine sinistro) da tutte le parti: dalla barra dell'applicazione alla maschera fissa e al contenuto delle tabelle:16 pixel
3) ASPETTARE RISPOSTA CAI PRIMA DI FARLA: il campo telefono e cellulare dei contatti deve prendere l'etichetta dal campo "Ruolo" in contatti e apertura (ora compilato mediante menu a tendina con tre voci: proprietario, custode e gestore).

**Comment by Bonny91** [comment]
- Se il campo coordinate è vuoto, non devono comparire le --;, ma solo la sola altitudine. Se non c'è nessuno dei due dati (né coordinate né altitudine), la parentesi scompare.
- Servizi: le informazioni devono comparire in ordine (l'ordine è quello di UNICOCAI, visualizzazione).
