### ISSUE TITLE
molto interessante ma non funziona.

### ISSUE THREAD

**Issue by lucabarattini** [loribonna/InfomontCAI#5]
Ciao! Ho provato a runnarlo seguendo quello che hai scritto sul readme: _npm serve_ e poi _npm run build_ ma niente da fare. Non runna :((

Da questo errore: 
(base) lucabarattini@Lucas-MBP-2 InfomontCAI-master % npm serve 
Unknown command: "serve"

To see a list of supported npm commands, run:
  npm help
(base) lucabarattini@Lucas-MBP-2 InfomontCAI-master % npm run build

> informont-cai@1.0.0 build
> ng build

sh: ng: command not found

**Comment by loribonna** [comment]
Ciao Luca, dall'errore di `npm run build` sembra che manchi il comando `ng`. Sei sicuro di avere installato angular/cli?

Se non lo hai fatto, dovresti fare `npm install` per scaricare tutto.
Detto questo e' molto che non torno su questo progetto quindi e' molto probabile che delle dipendenze siano cambiate.

Una volta installato prova `npm start` (non ricordo, ma puo' darsi che il `serve` sia un typo).
